name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pip
  - panel
  - bokeh
  - xmltodict
  - boto3
  - basemap
  - pip:
      - OpenVisus==2.2.141