name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - OpenVisus==2.2.141
  - panel
  - bokeh
  - xmltodict
  - boto3
  - basemap
  - pelicanfs
